apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: posstgres
  template:
    metadata:
      labels:
        component: posstgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        env:
          - name: POSTGRES_PASSWORD    #NOT PGPASSWORD, postgres change
            valueFrom:
              secretKeyRef:
                name: pgpassword 
                key:  PGPASSWORD

      
